language: cpp
os: linux
dist: focal
sudo: false

branches:
  only:
  - master

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_script:
  - sudo apt update -qq
  - sudo apt-get install libcurl4-openssl-dev

script:
  - make -j 4 all
  - make test
  - make clean
